# streaming content analytics

This notebook is used to clean the raw data.

1. Importing Libraries

In [263]:
import pandas as pd
import numpy as np
import json

2. Reading the csv file for cleaning

In [264]:
df = pd.read_csv("../data/raw/tmdb_5000_movies.csv")
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

3. Exploring the dataset

In [265]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [266]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [267]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

4. Deciding the columns we want to keep and drop

    - Droping ["homepage", "id", "keywords", "overview", "tagline", "production_companies", "title"] these columns because they are mostly textual columns which are not useful for our analysis, columns like "homepage" which is an url or "id" are not useful.

In [268]:
cols_to_drop = ["homepage", "id", "keywords", "overview", "tagline", "production_companies", "title"]

In [269]:
df.drop(columns=cols_to_drop, inplace=True)

In [270]:
df.head(1)

,budget,genres,original_language,original_title,popularity,production_countries,release_date,revenue,runtime,spoken_languages,status,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,Avatar,150.437577,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,7.2,11800

5. Checking status, to see how many unique statuses we have, and drop all status expect "Relased", because we want to do analysis on Movies that are being released.
    - We first checks for unique values in status
    - Then drop all rows were status is not released
    - Then drop the status column.
    - If we drop the status column in start, then we also have data of movies that are not released.

In [271]:
df["status"].unique()

array(['Released', 'Post Production', 'Rumored'], dtype=object)

In [272]:
status_to_drop = ["Post Production", "Rumored"]

In [273]:
df = df[~df["status"].isin(status_to_drop)]

In [274]:
df.drop(columns=["status"], inplace=True)

In [275]:
df.columns

Index(['budget', 'genres', 'original_language', 'original_title', 'popularity',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'vote_average', 'vote_count'],
      dtype='object')

6. Exploring dataset using head() and tail() methods

In [276]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4795 entries, 0 to 4802
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4795 non-null   int64
 1   genres                4795 non-null   object
 2   original_language     4795 non-null   object
 3   original_title        4795 non-null   object
 4   popularity            4795 non-null   float64
 5   production_countries  4795 non-null   object
 6   release_date          4794 non-null   object
 7   revenue               4795 non-null   int64
 8   runtime               4793 non-null   float64
 9   spoken_languages      4795 non-null   object
 10  vote_average          4795 non-null   float64
 11  vote_count            4795 non-null   int64
dtypes: float64(3), int64(3), object(6)
memory usage: 487.0+ KB

In [277]:
df.tail()

,budget,genres,original_language,original_title,popularity,production_countries,release_date,revenue,runtime,spoken_languages,vote_average,vote_count
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",es,El Mariachi,14.269792,"[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",en,Newlyweds,0.642552,[],2011-12-26,0,85.0,[],5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",en,"Signed, Sealed, Delivered",1.444476,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",7.0,6
4801,0,[],en,Shanghai Calling,0.857008,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",en,My Date with Drew,1.929883,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",6.3,16

7. We notice, we have columns where data is either 0 or an empty list. 
    - We are checking columns to find the number of these zero or empty list values.

In [278]:
cols_to_check_empty_list = ["genres", "production_countries", "spoken_languages"]
cols_int = ["revenue", "runtime"]
cols_float = ['budget', 'popularity']
cols_str = df.select_dtypes(object).columns.tolist()

In [279]:
for col in cols_to_check_empty_list:
    print(f"Values that contain emply list in {col}: {df[df[col] == "[]"].shape[0]}")

for col in cols_str:
    print(f"Values that contain emply string in {col}: {df[df[col] == ""].shape[0]}")

for col in cols_int + cols_float:
    print(f"Values that contain 0 in {col}: {df[df[col] == 0].shape[0]}")

Values that contain emply list in genres: 28
Values that contain emply list in production_countries: 171
Values that contain emply list in spoken_languages: 84
Values that contain emply string in genres: 0
Values that contain emply string in original_language: 0
Values that contain emply string in original_title: 0
Values that contain emply string in production_countries: 0
Values that contain emply string in release_date: 0
Values that contain emply string in spoken_languages: 0
Values that contain 0 in revenue: 1420
Values that contain 0 in runtime: 34
Values that contain 0 in budget: 1032
Values that contain 0 in popularity: 1

8. Replacing null values and zero's with NA, so we could drop them.

In [280]:
for col in cols_to_check_empty_list:
    df[col] = df[col].replace("[]", pd.NA)

for col in cols_int + cols_float:
    df[col] = df[col].replace(0, pd.NA)

In [281]:
for col in cols_to_check_empty_list:
    print(f"Values that contain emply list in {col}: {df[df[col] == "[]"].shape[0]}")

for col in cols_str:
    print(f"Values that contain emply string in {col}: {df[df[col] == ""].shape[0]}")

for col in cols_int + cols_float:
    print(f"Values that contain 0 in {col}: {df[df[col] == 0].shape[0]}")

Values that contain emply list in genres: 0
Values that contain emply list in production_countries: 0
Values that contain emply list in spoken_languages: 0
Values that contain emply string in genres: 0
Values that contain emply string in original_language: 0
Values that contain emply string in original_title: 0
Values that contain emply string in production_countries: 0
Values that contain emply string in release_date: 0
Values that contain emply string in spoken_languages: 0
Values that contain 0 in revenue: 0
Values that contain 0 in runtime: 0
Values that contain 0 in budget: 0
Values that contain 0 in popularity: 0

9. Droping NA values and duplicates

In [282]:
df.isnull().sum()

budget                  1032
genres                    28
original_language          0
original_title             0
popularity                 1
production_countries     171
release_date               1
revenue                 1420
runtime                   36
spoken_languages          84
vote_average               0
vote_count                 0
dtype: int64

In [283]:
df.dropna(inplace=True)

In [284]:
df.drop_duplicates(inplace=True)

In [285]:
df.isnull().sum()

budget                  0
genres                  0
original_language       0
original_title          0
popularity              0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
vote_average            0
vote_count              0
dtype: int64

In [286]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3210 entries, 0 to 4798
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                3210 non-null   object
 1   genres                3210 non-null   object
 2   original_language     3210 non-null   object
 3   original_title        3210 non-null   object
 4   popularity            3210 non-null   object
 5   production_countries  3210 non-null   object
 6   release_date          3210 non-null   object
 7   revenue               3210 non-null   object
 8   runtime               3210 non-null   object
 9   spoken_languages      3210 non-null   object
 10  vote_average          3210 non-null   float64
 11  vote_count            3210 non-null   int64
dtypes: float64(1), int64(1), object(10)
memory usage: 326.0+ KB

In [287]:
df.head()

,budget,genres,original_language,original_title,popularity,production_countries,release_date,revenue,runtime,spoken_languages,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,Avatar,150.437577,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",en,Pirates of the Caribbean: At World's End,139.082615,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,Spectre,107.376788,"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",en,The Dark Knight Rises,112.31295,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",en,John Carter,43.926995,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",6.1,2124

10. using Json to convert ["genres", "production_countries", "spoken_languages"] into python list.
    - Before: '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
    - After: [Action, Adventure, Fantasy, Science Fiction]

In [288]:
def parse_string(string):
    try:
        return [d["name"] for d in json.loads(string)]
    except Exception as e:
        print(f"Error is {e}")

In [289]:
df["genres"] = df["genres"].apply(parse_string)
df["production_countries"] = df["production_countries"].apply(parse_string)
df["spoken_languages"] = df["spoken_languages"].apply(parse_string)

11. Converting the datatypes of columns to those types where they better fit and reseting indexes.

In [291]:
df["release_date"] = pd.to_datetime(df["release_date"])

convert_to_int = ["runtime", "vote_count", "revenue"]
convert_to_Int64 = ["budget"]
convert_to_float = ["popularity", "vote_average"]

df[convert_to_int] = df[convert_to_int].astype(np.int64)
df[convert_to_Int64] = df[convert_to_Int64].astype("Int64")
df[convert_to_float] = df[convert_to_float].astype(np.float64)

df.reset_index(drop=True, inplace=True)

12. Rounding the popularty to decimal point of 2 for better and consistent analysis.

In [292]:
df["popularity"] = df["popularity"].round(2)

In [293]:
df.head()

,budget,genres,original_language,original_title,popularity,production_countries,release_date,revenue,runtime,spoken_languages,vote_average,vote_count
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",en,Avatar,150.44,"[United States of America, United Kingdom]",2009-12-10,2787965087,162,"[English, Español]",7.2,11800
1,300000000,"[Adventure, Fantasy, Action]",en,Pirates of the Caribbean: At World's End,139.08,[United States of America],2007-05-19,961000000,169,[English],6.9,4500
2,245000000,"[Action, Adventure, Crime]",en,Spectre,107.38,"[United Kingdom, United States of America]",2015-10-26,880674609,148,"[Français, English, Español, Italiano, Deutsch]",6.3,4466
3,250000000,"[Action, Crime, Drama, Thriller]",en,The Dark Knight Rises,112.31,[United States of America],2012-07-16,1084939099,165,[English],7.6,9106
4,260000000,"[Action, Adventure, Science Fiction]",en,John Carter,43.93,[United States of America],2012-03-07,284139100,132,[English],6.1,2124

13. Saving cleaned dataset file

In [295]:
df.to_csv("../data/processed/cleaned_dataset.csv", index=False)

- These three columns ["genres", "production_countries", "spoken_languages"] contains lists. We will explode them during Explorartory Data Analysis.
    - [Action, Adventure, Fantasy, Science Fiction]